# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-11-02 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_added_algorithm_selection'),
    ]

    operations = [
        migrations.AddField(
            model_name='knobcatalog',
            name='ishardware',
            field=models.BooleanField(default=False, verbose_name='is hardware knobs or not'),
        ),
    ]
