# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-06-23 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20200622_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='reward',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
